{
 "title": "PokeStats",
 "time": { "from": "now-14d", "to": "now" },
 "panels": [
  {
   "title": "General statistics of battles",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM battles LIMIT 50 "
    },
    {
     "rawSql": "SELECT AVG(quanity_rounds) FROM battles LIMIT 50 "
    }
   ]
  },
  {
   "title": "Battle schedule by day",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    DATE(created_at) AS battle_date,\n    COUNT(*) AS battle_count\nFROM\n    battles\nGROUP BY\n    battle_date\nORDER BY\n    battle_date;"
    }
   ]
  },
  {
   "title": "TOP-5 Poke by wins",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    poke,\n    COUNT(*) AS wins\nFROM\n    (\n        SELECT\n            CASE\n                WHEN select_is_win = TRUE THEN select_poke\n                ELSE opponent_poke\n            END AS poke\n        FROM\n            battles\n    )\nGROUP BY\n    poke\nORDER BY\n    wins DESC,\n    poke ASC\nLIMIT\n    5;"
    }
   ]
  },
  {
   "title": "Graph of the average number of rounds by day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n    DATE(created_at) AS battle_date,\n    AVG(quanity_rounds) AS avg_rounds\nFROM\n    battles\nGROUP BY\n    battle_date\nORDER BY\n    battle_date;"
    }
   ]
  },
  {
   "title": "Graph of the number of rounds by day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n    DATE(created_at) AS battle_date,\n    SUM(quanity_rounds) AS sum_rounds\nFROM\n    battles\nGROUP BY\n    battle_date\nORDER BY\n    battle_date;"
    }
   ]
  }
 ]
}